<?php

require_once '../commons/ReportPDF.php';
include_once '../model/bus_model.php';

$busObj = new Bus();
$busResult = $busObj->getAllBuses();

$pdf = new ReportPDF();
$pdf->AliasNbPages(); // Enable page numbers
$pdf->setReportTitle('Bus Fleet Details Report');

$pdf->AddPage("P", "A4"); // Add page after setting the title for Header() to pick it up

// Set initial content font and introductory text
$pdf->SetFont("Arial", "", 11);
$pdf->Cell(0, 10, 'This report was generated by Clint Barton as of ' . date("H:i:s, Y-m-d"), 0, 1, 'L');
$pdf->Ln(5); // Small space before the table

// Define table column widths
$colWidths = [
    20, // Vehicle Number
    20, // Category
    30, // Make
    25, // Model
    13, // Year
    15, // Capacity
    10, // A/C
    20, // Current KM
    30  // Status
];

// Define table headers
$headers = [
    'Vehicle No.',
    'Category',
    'Make',
    'Model',
    'Year',
    'Capacity',
    'A/C',
    'Current KM',
    'Status'
];

// Print table headers
$pdf->SetFont('Arial', 'B', 9);
$pdf->SetFillColor(200, 220, 255); // Lighter blue background for headers
$pdf->SetTextColor(0); // Black text for headers

for($i = 0;$i<count($headers);$i++){
    
    $pdf->Cell($colWidths[$i], 7, $headers[$i], 1, 0, 'C', true);
}

$pdf->Ln(); // New line after headers

$pdf->SetFont('Arial', '', 8);
$pdf->SetTextColor(0);

while($busRow = $busResult->fetch_assoc()){
    
    $ac = "";
    
    if($busRow["ac_available"]=="N"){
        $ac = "No";
    }
    else{
        $ac = "Yes";
    }
    
    $status = match((int)$busRow["bus_status"]){
        
        -1=>"Removed",
        0=>"Out Of Service",
        1=>"Operational",
        2=>"Service Due",
        3=>"In Service",
        4=>"Inspection Failed",
    };
    
    $pdf->Cell($colWidths[0], 6,$busRow["vehicle_no"], 1, 0, 'L');
    $pdf->Cell($colWidths[1], 6,$busRow["category_name"], 1, 0, 'L');
    $pdf->Cell($colWidths[2], 6,$busRow["make"], 1, 0, 'L');
    $pdf->Cell($colWidths[3], 6,$busRow["model"], 1, 0, 'L');
    $pdf->Cell($colWidths[4], 6,$busRow["year"], 1, 0, 'C');
    $pdf->Cell($colWidths[5], 6,number_format($busRow["capacity"]), 1, 0, 'R');
    $pdf->Cell($colWidths[6], 6,$ac, 1, 0, 'C');
    $pdf->Cell($colWidths[7], 6,number_format($busRow["current_mileage_km"]), 1, 0, 'R');
    $pdf->Cell($colWidths[8], 6,$status, 1, 1, 'L');
}



$pdf->Output();